### ISSUE TITLE
Building Error 

### ISSUE THREAD

**Issue by kaplanmartin** [Andrewiski/UISP-Tools#1]
Hello!

I am trying to build the image but got this error:

jessicas-MacBook-Pro:uisptools martinkaplan$ docker-compose -f ~/uisptools/docker-compose.yml up --force-recreate -d
Building uisptools
[+] Building 0.2s (1/2)                                                                                                                                                                                     
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.1s
 => => transferring dockerfile: 2B                                                                                                                                                                     0.0s
**failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount561288360/Dockerfile: no such file or directory**
ERROR: Service 'uisptools' failed to build : Build failed

**Comment by Andrewiski** [comment]
This project is not ready for production use and is a slow work in progress with plenty of bugs and features I want to add. I really haven't tested the docker-compose.yml outside of visual code so the docker-compose.yml inside of .devcontainer folder is the one that gets used there and tested as I dev.   I own to WISP in two different states so dev time is a little limited at the moment should free up as we get into the winter months.   What is it you are looking for in the application?

**Comment by kaplanmartin** [comment]
I also own a wisp and was curious if I could you use it as a base code for whatever I might need, such as batch updates, etc, etc.

**Comment by kaplanmartin** [comment]
How can I help?

**Comment by Andrewiski** [comment]
What level of developer would you rate yourself.?  I have grand visions but never enough time. When you dig into UISP you can see the are running ngix in a docker so injecting a html webserver into it is easy enough so the same url may or ma not be reused. Doesn't have to function this way but possible.  There is some much in UISP yet so much lacking.  Some thing off the top of my head.

DFS Event Detection - Auto Reboot as in my experince I have yet to have an actual this is always false in my area
DHCP Real Third party device support - Add api calls to edgemax routers to webhook dhcp leases and run through the router and find the mac address in the arp table on the lan interface
Auto Map Frequencey on Google Map.  -  We are missing heading so would need to enter sector heading but a visual map using tower sites and frequencies be awsome to include some airview to see competitors and site surveies.
Rouge DHCP detection - a simple ssh tcpdump and you can find the rouge mac address to disable the client station lan port until they get home to correct the misswire.  

I have more just a few off the top of my head.

**Comment by Andrewiski** [comment]
I have moved to dockerized containers and am now deploying to docker.io for prebuilt packaging of the application
